### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [jxmorris12/bm25_pt#1]
Hi,
Thanks for releasing this! Would you mind adding a license (ie MIT/Apache/CC0)?
Thank you!

**Comment by jxmorris12** [comment]
done!

**Comment by fakerybakery** [comment]
Thanks!

**Comment by sobin007** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
zpffly001, @marciohdo, @archie-winsor, @robin22333, @pandavips, @lolorenzo777, @amirfarajii, @bmoir23, @yyc13236, @horou-dsk, @lpbellier, @headwindz, @lizhifei2010, @aquaqamelob2, @Gameghostify, @sfyang2, @dreamingo88, @yeahlincoln, @sagar-pardhi, @aboveStars, @binlaniua, @Hansum, @masterlueth, @Mahsa-Bastankhah, @privateidentity, @Jinchengawu, @Austin5925, @Giwada, @Anjalipattani, @ugCrying, @ptspzy, @idabaicai, @Aaron3S, @wangjh7, @H2crypt0, @isecren, @Jarweb, @jdickman00, @menglingyu, @eltanin33, @jupitermandy, @jacky20221117, @MrKomish, @paulayo93, @szdbetter, @damnern12807, @zenoncao, @MarcosLopes-Dev, @flykickbird, @zavg
